/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.teller_app.teller_db.Address;
import com.wavemaker.teller_app.teller_db.Branch;
import com.wavemaker.teller_app.teller_db.Customer;
import com.wavemaker.teller_app.teller_db.service.AddressService;


/**
 * Controller object for domain model class Address.
 * @see Address
 */
@RestController("teller_db.AddressController")
@Api(value = "AddressController", description = "Exposes APIs to work with Address resource.")
@RequestMapping("/teller_db/Address")
public class AddressController {

    private static final Logger LOGGER = LoggerFactory.getLogger(AddressController.class);

    @Autowired
	@Qualifier("teller_db.AddressService")
	private AddressService addressService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Address instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Address createAddress(@RequestBody Address address) {
		LOGGER.debug("Create Address with information: {}" , address);

		address = addressService.create(address);
		LOGGER.debug("Created Address with information: {}" , address);

	    return address;
	}

    @ApiOperation(value = "Returns the Address instance associated with the given id.")
    @GetMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Address getAddress(@PathVariable("id") Integer id) {
        LOGGER.debug("Getting Address with id: {}" , id);

        Address foundAddress = addressService.getById(id);
        LOGGER.debug("Address details with id: {}" , foundAddress);

        return foundAddress;
    }

    @ApiOperation(value = "Updates the Address instance associated with the given id.")
    @PutMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Address editAddress(@PathVariable("id") Integer id, @RequestBody Address address) {
        LOGGER.debug("Editing Address with id: {}" , address.getId());

        address.setId(id);
        address = addressService.update(address);
        LOGGER.debug("Address details with id: {}" , address);

        return address;
    }
    
    @ApiOperation(value = "Partially updates the Address instance associated with the given id.")
    @PatchMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Address patchAddress(@PathVariable("id") Integer id, @RequestBody @MapTo(Address.class) Map<String, Object> addressPatch) {
        LOGGER.debug("Partially updating Address with id: {}" , id);

        Address address = addressService.partialUpdate(id, addressPatch);
        LOGGER.debug("Address details after partial update: {}" , address);

        return address;
    }

    @ApiOperation(value = "Deletes the Address instance associated with the given id.")
    @DeleteMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteAddress(@PathVariable("id") Integer id) {
        LOGGER.debug("Deleting Address with id: {}" , id);

        Address deletedAddress = addressService.delete(id);

        return deletedAddress != null;
    }

    /**
     * @deprecated Use {@link #findAddresses(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Address instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Address> searchAddressesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Addresses list by query filter:{}", (Object) queryFilters);
        return addressService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Address instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Address> findAddresses(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Addresses list by filter:", query);
        return addressService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Address instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Address> filterAddresses(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Addresses list by filter", query);
        return addressService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportAddresses(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return addressService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportAddressesAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Address.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> addressService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Address instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countAddresses( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Addresses");
		return addressService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getAddressAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return addressService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{id:.+}/branches")
    @ApiOperation(value = "Gets the branches instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Branch> findAssociatedBranches(@PathVariable("id") Integer id, Pageable pageable) {

        LOGGER.debug("Fetching all associated branches");
        return addressService.findAssociatedBranches(id, pageable);
    }

    @GetMapping(value="/{id:.+}/customers")
    @ApiOperation(value = "Gets the customers instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Customer> findAssociatedCustomers(@PathVariable("id") Integer id, Pageable pageable) {

        LOGGER.debug("Fetching all associated customers");
        return addressService.findAssociatedCustomers(id, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service AddressService instance
	 */
	protected void setAddressService(AddressService service) {
		this.addressService = service;
	}

}
