/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.teller_app.teller_db.Balance;
import com.wavemaker.teller_app.teller_db.service.BalanceService;


/**
 * Controller object for domain model class Balance.
 * @see Balance
 */
@RestController("teller_db.BalanceController")
@Api(value = "BalanceController", description = "Exposes APIs to work with Balance resource.")
@RequestMapping("/teller_db/Balance")
public class BalanceController {

    private static final Logger LOGGER = LoggerFactory.getLogger(BalanceController.class);

    @Autowired
	@Qualifier("teller_db.BalanceService")
	private BalanceService balanceService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Balance instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Balance createBalance(@RequestBody Balance balance) {
		LOGGER.debug("Create Balance with information: {}" , balance);

		balance = balanceService.create(balance);
		LOGGER.debug("Created Balance with information: {}" , balance);

	    return balance;
	}

    @ApiOperation(value = "Returns the Balance instance associated with the given id.")
    @GetMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Balance getBalance(@PathVariable("id") Integer id) {
        LOGGER.debug("Getting Balance with id: {}" , id);

        Balance foundBalance = balanceService.getById(id);
        LOGGER.debug("Balance details with id: {}" , foundBalance);

        return foundBalance;
    }

    @ApiOperation(value = "Updates the Balance instance associated with the given id.")
    @PutMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Balance editBalance(@PathVariable("id") Integer id, @RequestBody Balance balance) {
        LOGGER.debug("Editing Balance with id: {}" , balance.getId());

        balance.setId(id);
        balance = balanceService.update(balance);
        LOGGER.debug("Balance details with id: {}" , balance);

        return balance;
    }
    
    @ApiOperation(value = "Partially updates the Balance instance associated with the given id.")
    @PatchMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Balance patchBalance(@PathVariable("id") Integer id, @RequestBody @MapTo(Balance.class) Map<String, Object> balancePatch) {
        LOGGER.debug("Partially updating Balance with id: {}" , id);

        Balance balance = balanceService.partialUpdate(id, balancePatch);
        LOGGER.debug("Balance details after partial update: {}" , balance);

        return balance;
    }

    @ApiOperation(value = "Deletes the Balance instance associated with the given id.")
    @DeleteMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteBalance(@PathVariable("id") Integer id) {
        LOGGER.debug("Deleting Balance with id: {}" , id);

        Balance deletedBalance = balanceService.delete(id);

        return deletedBalance != null;
    }

    @GetMapping(value = "/accountNumber/{accountNumber}" )
    @ApiOperation(value = "Returns the matching Balance with given unique key values.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Balance getByAccountNumber(@PathVariable("accountNumber") int accountNumber) {
        LOGGER.debug("Getting Balance with uniques key AccountNumber");
        return balanceService.getByAccountNumber(accountNumber);
    }

    /**
     * @deprecated Use {@link #findBalances(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Balance instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Balance> searchBalancesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Balances list by query filter:{}", (Object) queryFilters);
        return balanceService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Balance instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Balance> findBalances(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Balances list by filter:", query);
        return balanceService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Balance instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Balance> filterBalances(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Balances list by filter", query);
        return balanceService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportBalances(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return balanceService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportBalancesAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Balance.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> balanceService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Balance instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countBalances( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Balances");
		return balanceService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getBalanceAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return balanceService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service BalanceService instance
	 */
	protected void setBalanceService(BalanceService service) {
		this.balanceService = service;
	}

}
