/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.teller_app.teller_db.Account;
import com.wavemaker.teller_app.teller_db.Branch;
import com.wavemaker.teller_app.teller_db.Manager;
import com.wavemaker.teller_app.teller_db.service.BranchService;


/**
 * Controller object for domain model class Branch.
 * @see Branch
 */
@RestController("teller_db.BranchController")
@Api(value = "BranchController", description = "Exposes APIs to work with Branch resource.")
@RequestMapping("/teller_db/Branch")
public class BranchController {

    private static final Logger LOGGER = LoggerFactory.getLogger(BranchController.class);

    @Autowired
	@Qualifier("teller_db.BranchService")
	private BranchService branchService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Branch instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Branch createBranch(@RequestBody Branch branch) {
		LOGGER.debug("Create Branch with information: {}" , branch);

		branch = branchService.create(branch);
		LOGGER.debug("Created Branch with information: {}" , branch);

	    return branch;
	}

    @ApiOperation(value = "Returns the Branch instance associated with the given id.")
    @GetMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Branch getBranch(@PathVariable("id") Integer id) {
        LOGGER.debug("Getting Branch with id: {}" , id);

        Branch foundBranch = branchService.getById(id);
        LOGGER.debug("Branch details with id: {}" , foundBranch);

        return foundBranch;
    }

    @ApiOperation(value = "Updates the Branch instance associated with the given id.")
    @PutMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Branch editBranch(@PathVariable("id") Integer id, @RequestBody Branch branch) {
        LOGGER.debug("Editing Branch with id: {}" , branch.getId());

        branch.setId(id);
        branch = branchService.update(branch);
        LOGGER.debug("Branch details with id: {}" , branch);

        return branch;
    }
    
    @ApiOperation(value = "Partially updates the Branch instance associated with the given id.")
    @PatchMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Branch patchBranch(@PathVariable("id") Integer id, @RequestBody @MapTo(Branch.class) Map<String, Object> branchPatch) {
        LOGGER.debug("Partially updating Branch with id: {}" , id);

        Branch branch = branchService.partialUpdate(id, branchPatch);
        LOGGER.debug("Branch details after partial update: {}" , branch);

        return branch;
    }

    @ApiOperation(value = "Deletes the Branch instance associated with the given id.")
    @DeleteMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteBranch(@PathVariable("id") Integer id) {
        LOGGER.debug("Deleting Branch with id: {}" , id);

        Branch deletedBranch = branchService.delete(id);

        return deletedBranch != null;
    }

    /**
     * @deprecated Use {@link #findBranches(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Branch instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Branch> searchBranchesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Branches list by query filter:{}", (Object) queryFilters);
        return branchService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Branch instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Branch> findBranches(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Branches list by filter:", query);
        return branchService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Branch instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Branch> filterBranches(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Branches list by filter", query);
        return branchService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportBranches(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return branchService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportBranchesAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Branch.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> branchService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Branch instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countBranches( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Branches");
		return branchService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getBranchAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return branchService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{id:.+}/accounts")
    @ApiOperation(value = "Gets the accounts instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Account> findAssociatedAccounts(@PathVariable("id") Integer id, Pageable pageable) {

        LOGGER.debug("Fetching all associated accounts");
        return branchService.findAssociatedAccounts(id, pageable);
    }

    @GetMapping(value="/{id:.+}/managers")
    @ApiOperation(value = "Gets the managers instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Manager> findAssociatedManagers(@PathVariable("id") Integer id, Pageable pageable) {

        LOGGER.debug("Fetching all associated managers");
        return branchService.findAssociatedManagers(id, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service BranchService instance
	 */
	protected void setBranchService(BranchService service) {
		this.branchService = service;
	}

}
