/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.teller_app.teller_db.DepositAccount;
import com.wavemaker.teller_app.teller_db.service.DepositAccountService;


/**
 * Controller object for domain model class DepositAccount.
 * @see DepositAccount
 */
@RestController("teller_db.DepositAccountController")
@Api(value = "DepositAccountController", description = "Exposes APIs to work with DepositAccount resource.")
@RequestMapping("/teller_db/DepositAccount")
public class DepositAccountController {

    private static final Logger LOGGER = LoggerFactory.getLogger(DepositAccountController.class);

    @Autowired
	@Qualifier("teller_db.DepositAccountService")
	private DepositAccountService depositAccountService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new DepositAccount instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public DepositAccount createDepositAccount(@RequestBody DepositAccount depositAccount) {
		LOGGER.debug("Create DepositAccount with information: {}" , depositAccount);

		depositAccount = depositAccountService.create(depositAccount);
		LOGGER.debug("Created DepositAccount with information: {}" , depositAccount);

	    return depositAccount;
	}

    @ApiOperation(value = "Returns the DepositAccount instance associated with the given id.")
    @GetMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public DepositAccount getDepositAccount(@PathVariable("id") Integer id) {
        LOGGER.debug("Getting DepositAccount with id: {}" , id);

        DepositAccount foundDepositAccount = depositAccountService.getById(id);
        LOGGER.debug("DepositAccount details with id: {}" , foundDepositAccount);

        return foundDepositAccount;
    }

    @ApiOperation(value = "Updates the DepositAccount instance associated with the given id.")
    @PutMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public DepositAccount editDepositAccount(@PathVariable("id") Integer id, @RequestBody DepositAccount depositAccount) {
        LOGGER.debug("Editing DepositAccount with id: {}" , depositAccount.getId());

        depositAccount.setId(id);
        depositAccount = depositAccountService.update(depositAccount);
        LOGGER.debug("DepositAccount details with id: {}" , depositAccount);

        return depositAccount;
    }
    
    @ApiOperation(value = "Partially updates the DepositAccount instance associated with the given id.")
    @PatchMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public DepositAccount patchDepositAccount(@PathVariable("id") Integer id, @RequestBody @MapTo(DepositAccount.class) Map<String, Object> depositAccountPatch) {
        LOGGER.debug("Partially updating DepositAccount with id: {}" , id);

        DepositAccount depositAccount = depositAccountService.partialUpdate(id, depositAccountPatch);
        LOGGER.debug("DepositAccount details after partial update: {}" , depositAccount);

        return depositAccount;
    }

    @ApiOperation(value = "Deletes the DepositAccount instance associated with the given id.")
    @DeleteMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteDepositAccount(@PathVariable("id") Integer id) {
        LOGGER.debug("Deleting DepositAccount with id: {}" , id);

        DepositAccount deletedDepositAccount = depositAccountService.delete(id);

        return deletedDepositAccount != null;
    }

    /**
     * @deprecated Use {@link #findDepositAccounts(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of DepositAccount instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<DepositAccount> searchDepositAccountsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering DepositAccounts list by query filter:{}", (Object) queryFilters);
        return depositAccountService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of DepositAccount instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<DepositAccount> findDepositAccounts(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering DepositAccounts list by filter:", query);
        return depositAccountService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of DepositAccount instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<DepositAccount> filterDepositAccounts(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering DepositAccounts list by filter", query);
        return depositAccountService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportDepositAccounts(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return depositAccountService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportDepositAccountsAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = DepositAccount.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> depositAccountService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of DepositAccount instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countDepositAccounts( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting DepositAccounts");
		return depositAccountService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getDepositAccountAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return depositAccountService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service DepositAccountService instance
	 */
	protected void setDepositAccountService(DepositAccountService service) {
		this.depositAccountService = service;
	}

}
