/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.teller_app.teller_db.Account;
import com.wavemaker.teller_app.teller_db.Manager;
import com.wavemaker.teller_app.teller_db.service.ManagerService;


/**
 * Controller object for domain model class Manager.
 * @see Manager
 */
@RestController("teller_db.ManagerController")
@Api(value = "ManagerController", description = "Exposes APIs to work with Manager resource.")
@RequestMapping("/teller_db/Manager")
public class ManagerController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ManagerController.class);

    @Autowired
	@Qualifier("teller_db.ManagerService")
	private ManagerService managerService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new Manager instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Manager createManager(@RequestBody Manager manager) {
		LOGGER.debug("Create Manager with information: {}" , manager);

		manager = managerService.create(manager);
		LOGGER.debug("Created Manager with information: {}" , manager);

	    return manager;
	}

    @ApiOperation(value = "Returns the Manager instance associated with the given id.")
    @GetMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Manager getManager(@PathVariable("id") Integer id) {
        LOGGER.debug("Getting Manager with id: {}" , id);

        Manager foundManager = managerService.getById(id);
        LOGGER.debug("Manager details with id: {}" , foundManager);

        return foundManager;
    }

    @ApiOperation(value = "Updates the Manager instance associated with the given id.")
    @PutMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Manager editManager(@PathVariable("id") Integer id, @RequestBody Manager manager) {
        LOGGER.debug("Editing Manager with id: {}" , manager.getId());

        manager.setId(id);
        manager = managerService.update(manager);
        LOGGER.debug("Manager details with id: {}" , manager);

        return manager;
    }
    
    @ApiOperation(value = "Partially updates the Manager instance associated with the given id.")
    @PatchMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Manager patchManager(@PathVariable("id") Integer id, @RequestBody @MapTo(Manager.class) Map<String, Object> managerPatch) {
        LOGGER.debug("Partially updating Manager with id: {}" , id);

        Manager manager = managerService.partialUpdate(id, managerPatch);
        LOGGER.debug("Manager details after partial update: {}" , manager);

        return manager;
    }

    @ApiOperation(value = "Deletes the Manager instance associated with the given id.")
    @DeleteMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteManager(@PathVariable("id") Integer id) {
        LOGGER.debug("Deleting Manager with id: {}" , id);

        Manager deletedManager = managerService.delete(id);

        return deletedManager != null;
    }

    @GetMapping(value = "/managerId/{managerId}" )
    @ApiOperation(value = "Returns the matching Manager with given unique key values.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Manager getByManagerId(@PathVariable("managerId") String managerId) {
        LOGGER.debug("Getting Manager with uniques key ManagerId");
        return managerService.getByManagerId(managerId);
    }

    /**
     * @deprecated Use {@link #findManagers(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Manager instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Manager> searchManagersByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Managers list by query filter:{}", (Object) queryFilters);
        return managerService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Manager instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Manager> findManagers(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Managers list by filter:", query);
        return managerService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Manager instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Manager> filterManagers(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Managers list by filter", query);
        return managerService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportManagers(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return managerService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportManagersAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = Manager.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> managerService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of Manager instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countManagers( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Managers");
		return managerService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getManagerAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return managerService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{id:.+}/accounts")
    @ApiOperation(value = "Gets the accounts instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Account> findAssociatedAccounts(@PathVariable("id") Integer id, Pageable pageable) {

        LOGGER.debug("Fetching all associated accounts");
        return managerService.findAssociatedAccounts(id, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service ManagerService instance
	 */
	protected void setManagerService(ManagerService service) {
		this.managerService = service;
	}

}
