/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import jakarta.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.wavemaker.teller_app.teller_db.service.Teller_dbQueryExecutorService;
import com.wavemaker.teller_app.teller_db.models.query.*;

@RestController(value = "Teller_db.QueryExecutionController")
@RequestMapping("/teller_db/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private Teller_dbQueryExecutorService queryService;

    @Autowired
	private ExportedFileManager exportedFileManager;

    @GetMapping(value = "/queries/GetAccountDetailsByCustomer")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Get all accounts for a customer along with branch info, branch address, and manager info")
    public Page<GetAccountDetailsByCustomerResponse> executeGetAccountDetailsByCustomer(@RequestParam(value = "customerId") Integer customerId, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: GetAccountDetailsByCustomer");
        Page<GetAccountDetailsByCustomerResponse> _result = queryService.executeGetAccountDetailsByCustomer(customerId, pageable);
        LOGGER.debug("got the result for named query: GetAccountDetailsByCustomer, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file url for query GetAccountDetailsByCustomer")
    @PostMapping(value = "/queries/GetAccountDetailsByCustomer/export")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportGetAccountDetailsByCustomer(@RequestParam(value = "customerId") Integer customerId, @RequestBody ExportOptions exportOptions, Pageable pageable) {
        LOGGER.debug("Exporting named query: GetAccountDetailsByCustomer");

        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = "GetAccountDetailsByCustomer";
        }
        exportedFileName += exportOptions.getExportType().getExtension();

        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName,
                        outputStream -> queryService.exportGetAccountDetailsByCustomer(customerId,  exportOptions, pageable, outputStream));

        return new StringWrapper(exportedUrl);
    }

    @GetMapping(value = "/queries/GetDepositAccountsByCustomer")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Get all deposit accounts linked to a customer's accounts")
    public Page<GetDepositAccountsByCustomerResponse> executeGetDepositAccountsByCustomer(@RequestParam(value = "customerId") Integer customerId, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: GetDepositAccountsByCustomer");
        Page<GetDepositAccountsByCustomerResponse> _result = queryService.executeGetDepositAccountsByCustomer(customerId, pageable);
        LOGGER.debug("got the result for named query: GetDepositAccountsByCustomer, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file url for query GetDepositAccountsByCustomer")
    @PostMapping(value = "/queries/GetDepositAccountsByCustomer/export")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportGetDepositAccountsByCustomer(@RequestParam(value = "customerId") Integer customerId, @RequestBody ExportOptions exportOptions, Pageable pageable) {
        LOGGER.debug("Exporting named query: GetDepositAccountsByCustomer");

        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = "GetDepositAccountsByCustomer";
        }
        exportedFileName += exportOptions.getExportType().getExtension();

        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName,
                        outputStream -> queryService.exportGetDepositAccountsByCustomer(customerId,  exportOptions, pageable, outputStream));

        return new StringWrapper(exportedUrl);
    }

    @GetMapping(value = "/queries/GetCustomerDetails")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Get all customer info plus address details using customer primary key id")
    public GetCustomerDetailsResponse executeGetCustomerDetails(@RequestParam(value = "customerId") Integer customerId, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: GetCustomerDetails");
        GetCustomerDetailsResponse _result = queryService.executeGetCustomerDetails(customerId);
        LOGGER.debug("got the result for named query: GetCustomerDetails, result:{}", _result);
        return _result;
    }

    @GetMapping(value = "/queries/getCustomerListData")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns one row per customer with aggregated total balance (SUM), account count (COUNT), and account status summary (GROUP_CONCAT), joined with branch, address, and manager details.")
    public Page<GetCustomerListDataResponse> executeGetCustomerListData(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: getCustomerListData");
        Page<GetCustomerListDataResponse> _result = queryService.executeGetCustomerListData(pageable);
        LOGGER.debug("got the result for named query: getCustomerListData, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file url for query getCustomerListData")
    @PostMapping(value = "/queries/getCustomerListData/export")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportGetCustomerListData(@RequestBody ExportOptions exportOptions, Pageable pageable) {
        LOGGER.debug("Exporting named query: getCustomerListData");

        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = "getCustomerListData";
        }
        exportedFileName += exportOptions.getExportType().getExtension();

        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName,
                        outputStream -> queryService.exportGetCustomerListData( exportOptions, pageable, outputStream));

        return new StringWrapper(exportedUrl);
    }

}
