/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.teller_app.teller_db.TransactionHistory;
import com.wavemaker.teller_app.teller_db.service.TransactionHistoryService;


/**
 * Controller object for domain model class TransactionHistory.
 * @see TransactionHistory
 */
@RestController("teller_db.TransactionHistoryController")
@Api(value = "TransactionHistoryController", description = "Exposes APIs to work with TransactionHistory resource.")
@RequestMapping("/teller_db/TransactionHistory")
public class TransactionHistoryController {

    private static final Logger LOGGER = LoggerFactory.getLogger(TransactionHistoryController.class);

    @Autowired
	@Qualifier("teller_db.TransactionHistoryService")
	private TransactionHistoryService transactionHistoryService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new TransactionHistory instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public TransactionHistory createTransactionHistory(@RequestBody TransactionHistory transactionHistory) {
		LOGGER.debug("Create TransactionHistory with information: {}" , transactionHistory);

		transactionHistory = transactionHistoryService.create(transactionHistory);
		LOGGER.debug("Created TransactionHistory with information: {}" , transactionHistory);

	    return transactionHistory;
	}

    @ApiOperation(value = "Returns the TransactionHistory instance associated with the given id.")
    @GetMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public TransactionHistory getTransactionHistory(@PathVariable("id") Integer id) {
        LOGGER.debug("Getting TransactionHistory with id: {}" , id);

        TransactionHistory foundTransactionHistory = transactionHistoryService.getById(id);
        LOGGER.debug("TransactionHistory details with id: {}" , foundTransactionHistory);

        return foundTransactionHistory;
    }

    @ApiOperation(value = "Updates the TransactionHistory instance associated with the given id.")
    @PutMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public TransactionHistory editTransactionHistory(@PathVariable("id") Integer id, @RequestBody TransactionHistory transactionHistory) {
        LOGGER.debug("Editing TransactionHistory with id: {}" , transactionHistory.getId());

        transactionHistory.setId(id);
        transactionHistory = transactionHistoryService.update(transactionHistory);
        LOGGER.debug("TransactionHistory details with id: {}" , transactionHistory);

        return transactionHistory;
    }
    
    @ApiOperation(value = "Partially updates the TransactionHistory instance associated with the given id.")
    @PatchMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public TransactionHistory patchTransactionHistory(@PathVariable("id") Integer id, @RequestBody @MapTo(TransactionHistory.class) Map<String, Object> transactionHistoryPatch) {
        LOGGER.debug("Partially updating TransactionHistory with id: {}" , id);

        TransactionHistory transactionHistory = transactionHistoryService.partialUpdate(id, transactionHistoryPatch);
        LOGGER.debug("TransactionHistory details after partial update: {}" , transactionHistory);

        return transactionHistory;
    }

    @ApiOperation(value = "Deletes the TransactionHistory instance associated with the given id.")
    @DeleteMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteTransactionHistory(@PathVariable("id") Integer id) {
        LOGGER.debug("Deleting TransactionHistory with id: {}" , id);

        TransactionHistory deletedTransactionHistory = transactionHistoryService.delete(id);

        return deletedTransactionHistory != null;
    }

    /**
     * @deprecated Use {@link #findTransactionHistories(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of TransactionHistory instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<TransactionHistory> searchTransactionHistoriesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering TransactionHistories list by query filter:{}", (Object) queryFilters);
        return transactionHistoryService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of TransactionHistory instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<TransactionHistory> findTransactionHistories(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering TransactionHistories list by filter:", query);
        return transactionHistoryService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of TransactionHistory instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<TransactionHistory> filterTransactionHistories(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering TransactionHistories list by filter", query);
        return transactionHistoryService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportTransactionHistories(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return transactionHistoryService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportTransactionHistoriesAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = TransactionHistory.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> transactionHistoryService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of TransactionHistory instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countTransactionHistories( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting TransactionHistories");
		return transactionHistoryService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getTransactionHistoryAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return transactionHistoryService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service TransactionHistoryService instance
	 */
	protected void setTransactionHistoryService(TransactionHistoryService service) {
		this.transactionHistoryService = service;
	}

}
