/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Account generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`account`", uniqueConstraints = {
            @UniqueConstraint(name = "`unique_account_number`", columnNames = {"`account_number`"})})
public class Account implements Serializable {

    private Integer id;
    private int accountNumber;
    private String firstName;
    private String lastName;
    private String status;
    private String type;
    private String activatedFrom;
    private String activateTo;
    private String customerId;
    private int branchId;
    private String managerId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private Branch branch;
    private Customer customer;
    private Manager manager;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`account_number`", nullable = false, scale = 0, precision = 10)
    public int getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(int accountNumber) {
        this.accountNumber = accountNumber;
    }

    @Column(name = "`first_name`", nullable = true, length = 255)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "`last_name`", nullable = true, length = 255)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "`status`", nullable = true, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`type`", nullable = true, length = 255)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "`activated_from`", nullable = true, length = 255)
    public String getActivatedFrom() {
        return this.activatedFrom;
    }

    public void setActivatedFrom(String activatedFrom) {
        this.activatedFrom = activatedFrom;
    }

    @Column(name = "`activate_to`", nullable = true, length = 255)
    public String getActivateTo() {
        return this.activateTo;
    }

    public void setActivateTo(String activateTo) {
        this.activateTo = activateTo;
    }

    @Column(name = "`customer_id`", nullable = false, length = 255)
    public String getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    @Column(name = "`branch_id`", nullable = false, scale = 0, precision = 10)
    public int getBranchId() {
        return this.branchId;
    }

    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    @Column(name = "`manager_id`", nullable = false, length = 255)
    public String getManagerId() {
        return this.managerId;
    }

    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    @Column(name = "`created_at`", nullable = true)
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Column(name = "`updated_at`", nullable = true)
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`branch_id`", referencedColumnName = "`id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_account_TO_branch_braAnbGW`"))
    @Fetch(FetchMode.JOIN)
    public Branch getBranch() {
        return this.branch;
    }

    public void setBranch(Branch branch) {
        if(branch != null) {
            this.branchId = branch.getId();
        }

        this.branch = branch;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`customer_id`", referencedColumnName = "`customer_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`fk_account_To_customer`"))
    @Fetch(FetchMode.JOIN)
    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        if(customer != null) {
            this.customerId = customer.getCustomerId();
        }

        this.customer = customer;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`manager_id`", referencedColumnName = "`manager_id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`fk_account_To_manager`"))
    @Fetch(FetchMode.JOIN)
    public Manager getManager() {
        return this.manager;
    }

    public void setManager(Manager manager) {
        if(manager != null) {
            this.managerId = manager.getManagerId();
        }

        this.manager = manager;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Account)) return false;
        final Account account = (Account) o;
        return Objects.equals(getId(), account.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
