/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.time.LocalDateTime;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * DepositAccount generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`deposit_account`")
public class DepositAccount implements Serializable {

    private Integer id;
    private Double termDeposit;
    private Double maturityAmount;
    private Date depositedAt;
    private Date maturedAt;
    private int accountNumber;
    private String status;
    private Double rateOfInterest;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private Account account;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`term_deposit`", nullable = true, scale = 2, precision = 10)
    public Double getTermDeposit() {
        return this.termDeposit;
    }

    public void setTermDeposit(Double termDeposit) {
        this.termDeposit = termDeposit;
    }

    @Column(name = "`maturity_amount`", nullable = true, scale = 2, precision = 10)
    public Double getMaturityAmount() {
        return this.maturityAmount;
    }

    public void setMaturityAmount(Double maturityAmount) {
        this.maturityAmount = maturityAmount;
    }

    @Column(name = "`deposited_at`", nullable = true)
    public Date getDepositedAt() {
        return this.depositedAt;
    }

    public void setDepositedAt(Date depositedAt) {
        this.depositedAt = depositedAt;
    }

    @Column(name = "`matured_at`", nullable = true)
    public Date getMaturedAt() {
        return this.maturedAt;
    }

    public void setMaturedAt(Date maturedAt) {
        this.maturedAt = maturedAt;
    }

    @Column(name = "`account_number`", nullable = false, scale = 0, precision = 10)
    public int getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(int accountNumber) {
        this.accountNumber = accountNumber;
    }

    @Column(name = "`status`", nullable = true, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`rate_of_interest`", nullable = true, scale = 2, precision = 10)
    public Double getRateOfInterest() {
        return this.rateOfInterest;
    }

    public void setRateOfInterest(Double rateOfInterest) {
        this.rateOfInterest = rateOfInterest;
    }

    @Column(name = "`created_at`", nullable = true)
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Column(name = "`updated_at`", nullable = true)
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`account_number`", referencedColumnName = "`account_number`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`fk_deposit_account_To_account`"))
    @Fetch(FetchMode.JOIN)
    public Account getAccount() {
        return this.account;
    }

    public void setAccount(Account account) {
        if(account != null) {
            this.accountNumber = account.getAccountNumber();
        }

        this.account = account;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DepositAccount)) return false;
        final DepositAccount depositAccount = (DepositAccount) o;
        return Objects.equals(getId(), depositAccount.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
