/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TransactionHistory generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`transaction_history`")
public class TransactionHistory implements Serializable {

    private Integer id;
    private int accountNumber;
    private String transactionType;
    private Double amount;
    private Double totalAmount;
    private String status;
    private LocalDateTime transactedAt;
    private Account account;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`account_number`", nullable = false, scale = 0, precision = 10)
    public int getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(int accountNumber) {
        this.accountNumber = accountNumber;
    }

    @Column(name = "`transaction_type`", nullable = true, length = 255)
    public String getTransactionType() {
        return this.transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    @Column(name = "`amount`", nullable = true, scale = 2, precision = 10)
    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    @Column(name = "`total_amount`", nullable = true, scale = 2, precision = 10)
    public Double getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    @Column(name = "`status`", nullable = true, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`transacted_at`", nullable = true)
    public LocalDateTime getTransactedAt() {
        return this.transactedAt;
    }

    public void setTransactedAt(LocalDateTime transactedAt) {
        this.transactedAt = transactedAt;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`account_number`", referencedColumnName = "`account_number`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`fk_transaction_history_To_account`"))
    @Fetch(FetchMode.JOIN)
    public Account getAccount() {
        return this.account;
    }

    public void setAccount(Account account) {
        if(account != null) {
            this.accountNumber = account.getAccountNumber();
        }

        this.account = account;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TransactionHistory)) return false;
        final TransactionHistory transactionHistory = (TransactionHistory) o;
        return Objects.equals(getId(), transactionHistory.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
