/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Address;
import com.wavemaker.teller_app.teller_db.Branch;
import com.wavemaker.teller_app.teller_db.Customer;

/**
 * Service object for domain model class {@link Address}.
 */
public interface AddressService {

    /**
     * Creates a new Address. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Address if any.
     *
     * @param address Details of the Address to be created; value cannot be null.
     * @return The newly created Address.
     */
    Address create(@Valid Address address);


	/**
     * Returns Address by given id if exists.
     *
     * @param addressId The id of the Address to get; value cannot be null.
     * @return Address associated with the given addressId.
	 * @throws EntityNotFoundException If no Address is found.
     */
    Address getById(Integer addressId);

    /**
     * Find and return the Address by given id if exists, returns null otherwise.
     *
     * @param addressId The id of the Address to get; value cannot be null.
     * @return Address associated with the given addressId.
     */
    Address findById(Integer addressId);

	/**
     * Find and return the list of Addresses by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param addressIds The id's of the Address to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Addresses associated with the given addressIds.
     */
    List<Address> findByMultipleIds(List<Integer> addressIds, boolean orderedReturn);


    /**
     * Updates the details of an existing Address. It replaces all fields of the existing Address with the given address.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Address if any.
     *
     * @param address The details of the Address to be updated; value cannot be null.
     * @return The updated Address.
     * @throws EntityNotFoundException if no Address is found with given input.
     */
    Address update(@Valid Address address);


    /**
     * Partially updates the details of an existing Address. It updates only the
     * fields of the existing Address which are passed in the addressPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Address if any.
     *
     * @param addressId The id of the Address to be deleted; value cannot be null.
     * @param addressPatch The partial data of Address which is supposed to be updated; value cannot be null.
     * @return The updated Address.
     * @throws EntityNotFoundException if no Address is found with given input.
     */
    Address partialUpdate(Integer addressId, Map<String, Object> addressPatch);

    /**
     * Deletes an existing Address with the given id.
     *
     * @param addressId The id of the Address to be deleted; value cannot be null.
     * @return The deleted Address.
     * @throws EntityNotFoundException if no Address found with the given id.
     */
    Address delete(Integer addressId);

    /**
     * Deletes an existing Address with the given object.
     *
     * @param address The instance of the Address to be deleted; value cannot be null.
     */
    void delete(Address address);

    /**
     * Find all Addresses matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Addresses.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Address> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Addresses matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Addresses.
     *
     * @see Pageable
     * @see Page
     */
    Page<Address> findAll(String query, Pageable pageable);

    /**
     * Exports all Addresses matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Addresses matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Addresses in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Address.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated branches for given Address id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Branch instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Branch> findAssociatedBranches(Integer id, Pageable pageable);

    /*
     * Returns the associated customers for given Address id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Customer instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Customer> findAssociatedCustomers(Integer id, Pageable pageable);

}
