/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Address;
import com.wavemaker.teller_app.teller_db.Branch;
import com.wavemaker.teller_app.teller_db.Customer;


/**
 * ServiceImpl object for domain model class Address.
 *
 * @see Address
 */
@Service("teller_db.AddressService")
@Validated
@EntityService(entityClass = Address.class, serviceId = "teller_db")
public class AddressServiceImpl implements AddressService {

    private static final Logger LOGGER = LoggerFactory.getLogger(AddressServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("teller_db.CustomerService")
    private CustomerService customerService;

    @Lazy
    @Autowired
    @Qualifier("teller_db.BranchService")
    private BranchService branchService;

    @Autowired
    @Qualifier("teller_db.AddressDao")
    private WMGenericDao<Address, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<Address, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Address create(Address address) {
        LOGGER.debug("Creating a new Address with information: {}", address);

        Address addressCreated = this.wmGenericDao.create(address);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(addressCreated);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Address getById(Integer addressId) {
        LOGGER.debug("Finding Address by id: {}", addressId);
        return this.wmGenericDao.findById(addressId);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Address findById(Integer addressId) {
        LOGGER.debug("Finding Address by id: {}", addressId);
        try {
            return this.wmGenericDao.findById(addressId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Address found with id: {}", addressId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public List<Address> findByMultipleIds(List<Integer> addressIds, boolean orderedReturn) {
        LOGGER.debug("Finding Addresses by ids: {}", addressIds);

        return this.wmGenericDao.findByMultipleIds(addressIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "teller_dbTransactionManager")
    @Override
    public Address update(Address address) {
        LOGGER.debug("Updating Address with information: {}", address);

        this.wmGenericDao.update(address);
        this.wmGenericDao.refresh(address);

        return address;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Address partialUpdate(Integer addressId, Map<String, Object>addressPatch) {
        LOGGER.debug("Partially Updating the Address with id: {}", addressId);

        Address address = getById(addressId);

        try {
            ObjectReader addressReader = WMObjectMapper.getInstance().reader().forType(Address.class).withValueToUpdate(address);
            address = addressReader.readValue(WMObjectMapper.getInstance().writeValueAsString(addressPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", addressPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        address = update(address);

        return address;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Address delete(Integer addressId) {
        LOGGER.debug("Deleting Address with id: {}", addressId);
        Address deleted = this.wmGenericDao.findById(addressId);
        if (deleted == null) {
            LOGGER.debug("No Address found with id: {}", addressId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Address.class.getSimpleName(), addressId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public void delete(Address address) {
        LOGGER.debug("Deleting Address with {}", address);
        this.wmGenericDao.delete(address);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Address> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Addresses");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Address> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Addresses");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service teller_db for table Address to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service teller_db for table Address to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Branch> findAssociatedBranches(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated branches");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("address.id = '" + id + "'");

        return branchService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Customer> findAssociatedCustomers(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated customers");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("address.id = '" + id + "'");

        return customerService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service CustomerService instance
     */
    protected void setCustomerService(CustomerService service) {
        this.customerService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service BranchService instance
     */
    protected void setBranchService(BranchService service) {
        this.branchService = service;
    }

}
