/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Balance;


/**
 * ServiceImpl object for domain model class Balance.
 *
 * @see Balance
 */
@Service("teller_db.BalanceService")
@Validated
@EntityService(entityClass = Balance.class, serviceId = "teller_db")
public class BalanceServiceImpl implements BalanceService {

    private static final Logger LOGGER = LoggerFactory.getLogger(BalanceServiceImpl.class);


    @Autowired
    @Qualifier("teller_db.BalanceDao")
    private WMGenericDao<Balance, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<Balance, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Balance create(Balance balance) {
        LOGGER.debug("Creating a new Balance with information: {}", balance);

        Balance balanceCreated = this.wmGenericDao.create(balance);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(balanceCreated);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Balance getById(Integer balanceId) {
        LOGGER.debug("Finding Balance by id: {}", balanceId);
        return this.wmGenericDao.findById(balanceId);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Balance findById(Integer balanceId) {
        LOGGER.debug("Finding Balance by id: {}", balanceId);
        try {
            return this.wmGenericDao.findById(balanceId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Balance found with id: {}", balanceId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public List<Balance> findByMultipleIds(List<Integer> balanceIds, boolean orderedReturn) {
        LOGGER.debug("Finding Balances by ids: {}", balanceIds);

        return this.wmGenericDao.findByMultipleIds(balanceIds, orderedReturn);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Balance getByAccountNumber(int accountNumber) {
        Map<String, Object> accountNumberMap = new HashMap<>();
        accountNumberMap.put("accountNumber", accountNumber);

        LOGGER.debug("Finding Balance by unique keys: {}", accountNumberMap);
        return this.wmGenericDao.findByUniqueKey(accountNumberMap);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "teller_dbTransactionManager")
    @Override
    public Balance update(Balance balance) {
        LOGGER.debug("Updating Balance with information: {}", balance);

        this.wmGenericDao.update(balance);
        this.wmGenericDao.refresh(balance);

        return balance;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Balance partialUpdate(Integer balanceId, Map<String, Object>balancePatch) {
        LOGGER.debug("Partially Updating the Balance with id: {}", balanceId);

        Balance balance = getById(balanceId);

        try {
            ObjectReader balanceReader = WMObjectMapper.getInstance().reader().forType(Balance.class).withValueToUpdate(balance);
            balance = balanceReader.readValue(WMObjectMapper.getInstance().writeValueAsString(balancePatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", balancePatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        balance = update(balance);

        return balance;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Balance delete(Integer balanceId) {
        LOGGER.debug("Deleting Balance with id: {}", balanceId);
        Balance deleted = this.wmGenericDao.findById(balanceId);
        if (deleted == null) {
            LOGGER.debug("No Balance found with id: {}", balanceId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Balance.class.getSimpleName(), balanceId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public void delete(Balance balance) {
        LOGGER.debug("Deleting Balance with {}", balance);
        this.wmGenericDao.delete(balance);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Balance> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Balances");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Balance> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Balances");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service teller_db for table Balance to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service teller_db for table Balance to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
