/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Balance;

/**
 * Service object for domain model class {@link Balance}.
 */
public interface BalanceService {

    /**
     * Creates a new Balance. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Balance if any.
     *
     * @param balance Details of the Balance to be created; value cannot be null.
     * @return The newly created Balance.
     */
    Balance create(@Valid Balance balance);


	/**
     * Returns Balance by given id if exists.
     *
     * @param balanceId The id of the Balance to get; value cannot be null.
     * @return Balance associated with the given balanceId.
	 * @throws EntityNotFoundException If no Balance is found.
     */
    Balance getById(Integer balanceId);

    /**
     * Find and return the Balance by given id if exists, returns null otherwise.
     *
     * @param balanceId The id of the Balance to get; value cannot be null.
     * @return Balance associated with the given balanceId.
     */
    Balance findById(Integer balanceId);

	/**
     * Find and return the list of Balances by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param balanceIds The id's of the Balance to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Balances associated with the given balanceIds.
     */
    List<Balance> findByMultipleIds(List<Integer> balanceIds, boolean orderedReturn);

    /**
     * Find and return the Balance for given accountNumber  if exists.
     *
     * @param accountNumber value of accountNumber; value cannot be null.
     * @return Balance associated with the given inputs.
     * @throws EntityNotFoundException if no matching Balance found.
     */
    Balance getByAccountNumber(int accountNumber);

    /**
     * Updates the details of an existing Balance. It replaces all fields of the existing Balance with the given balance.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Balance if any.
     *
     * @param balance The details of the Balance to be updated; value cannot be null.
     * @return The updated Balance.
     * @throws EntityNotFoundException if no Balance is found with given input.
     */
    Balance update(@Valid Balance balance);


    /**
     * Partially updates the details of an existing Balance. It updates only the
     * fields of the existing Balance which are passed in the balancePatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Balance if any.
     *
     * @param balanceId The id of the Balance to be deleted; value cannot be null.
     * @param balancePatch The partial data of Balance which is supposed to be updated; value cannot be null.
     * @return The updated Balance.
     * @throws EntityNotFoundException if no Balance is found with given input.
     */
    Balance partialUpdate(Integer balanceId, Map<String, Object> balancePatch);

    /**
     * Deletes an existing Balance with the given id.
     *
     * @param balanceId The id of the Balance to be deleted; value cannot be null.
     * @return The deleted Balance.
     * @throws EntityNotFoundException if no Balance found with the given id.
     */
    Balance delete(Integer balanceId);

    /**
     * Deletes an existing Balance with the given object.
     *
     * @param balance The instance of the Balance to be deleted; value cannot be null.
     */
    void delete(Balance balance);

    /**
     * Find all Balances matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Balances.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Balance> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Balances matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Balances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Balance> findAll(String query, Pageable pageable);

    /**
     * Exports all Balances matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Balances matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Balances in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Balance.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}
