/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Account;
import com.wavemaker.teller_app.teller_db.Branch;
import com.wavemaker.teller_app.teller_db.Manager;

/**
 * Service object for domain model class {@link Branch}.
 */
public interface BranchService {

    /**
     * Creates a new Branch. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Branch if any.
     *
     * @param branch Details of the Branch to be created; value cannot be null.
     * @return The newly created Branch.
     */
    Branch create(@Valid Branch branch);


	/**
     * Returns Branch by given id if exists.
     *
     * @param branchId The id of the Branch to get; value cannot be null.
     * @return Branch associated with the given branchId.
	 * @throws EntityNotFoundException If no Branch is found.
     */
    Branch getById(Integer branchId);

    /**
     * Find and return the Branch by given id if exists, returns null otherwise.
     *
     * @param branchId The id of the Branch to get; value cannot be null.
     * @return Branch associated with the given branchId.
     */
    Branch findById(Integer branchId);

	/**
     * Find and return the list of Branches by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param branchIds The id's of the Branch to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Branches associated with the given branchIds.
     */
    List<Branch> findByMultipleIds(List<Integer> branchIds, boolean orderedReturn);


    /**
     * Updates the details of an existing Branch. It replaces all fields of the existing Branch with the given branch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Branch if any.
     *
     * @param branch The details of the Branch to be updated; value cannot be null.
     * @return The updated Branch.
     * @throws EntityNotFoundException if no Branch is found with given input.
     */
    Branch update(@Valid Branch branch);


    /**
     * Partially updates the details of an existing Branch. It updates only the
     * fields of the existing Branch which are passed in the branchPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Branch if any.
     *
     * @param branchId The id of the Branch to be deleted; value cannot be null.
     * @param branchPatch The partial data of Branch which is supposed to be updated; value cannot be null.
     * @return The updated Branch.
     * @throws EntityNotFoundException if no Branch is found with given input.
     */
    Branch partialUpdate(Integer branchId, Map<String, Object> branchPatch);

    /**
     * Deletes an existing Branch with the given id.
     *
     * @param branchId The id of the Branch to be deleted; value cannot be null.
     * @return The deleted Branch.
     * @throws EntityNotFoundException if no Branch found with the given id.
     */
    Branch delete(Integer branchId);

    /**
     * Deletes an existing Branch with the given object.
     *
     * @param branch The instance of the Branch to be deleted; value cannot be null.
     */
    void delete(Branch branch);

    /**
     * Find all Branches matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Branches.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Branch> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Branches matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Branches.
     *
     * @see Pageable
     * @see Page
     */
    Page<Branch> findAll(String query, Pageable pageable);

    /**
     * Exports all Branches matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Branches matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Branches in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Branch.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated accounts for given Branch id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Account instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Account> findAssociatedAccounts(Integer id, Pageable pageable);

    /*
     * Returns the associated managers for given Branch id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Manager instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Manager> findAssociatedManagers(Integer id, Pageable pageable);

}
