/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Account;
import com.wavemaker.teller_app.teller_db.Branch;
import com.wavemaker.teller_app.teller_db.Manager;


/**
 * ServiceImpl object for domain model class Branch.
 *
 * @see Branch
 */
@Service("teller_db.BranchService")
@Validated
@EntityService(entityClass = Branch.class, serviceId = "teller_db")
public class BranchServiceImpl implements BranchService {

    private static final Logger LOGGER = LoggerFactory.getLogger(BranchServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("teller_db.ManagerService")
    private ManagerService managerService;

    @Lazy
    @Autowired
    @Qualifier("teller_db.AccountService")
    private AccountService accountService;

    @Autowired
    @Qualifier("teller_db.BranchDao")
    private WMGenericDao<Branch, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<Branch, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Branch create(Branch branch) {
        LOGGER.debug("Creating a new Branch with information: {}", branch);

        Branch branchCreated = this.wmGenericDao.create(branch);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(branchCreated);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Branch getById(Integer branchId) {
        LOGGER.debug("Finding Branch by id: {}", branchId);
        return this.wmGenericDao.findById(branchId);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Branch findById(Integer branchId) {
        LOGGER.debug("Finding Branch by id: {}", branchId);
        try {
            return this.wmGenericDao.findById(branchId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Branch found with id: {}", branchId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public List<Branch> findByMultipleIds(List<Integer> branchIds, boolean orderedReturn) {
        LOGGER.debug("Finding Branches by ids: {}", branchIds);

        return this.wmGenericDao.findByMultipleIds(branchIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "teller_dbTransactionManager")
    @Override
    public Branch update(Branch branch) {
        LOGGER.debug("Updating Branch with information: {}", branch);

        this.wmGenericDao.update(branch);
        this.wmGenericDao.refresh(branch);

        return branch;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Branch partialUpdate(Integer branchId, Map<String, Object>branchPatch) {
        LOGGER.debug("Partially Updating the Branch with id: {}", branchId);

        Branch branch = getById(branchId);

        try {
            ObjectReader branchReader = WMObjectMapper.getInstance().reader().forType(Branch.class).withValueToUpdate(branch);
            branch = branchReader.readValue(WMObjectMapper.getInstance().writeValueAsString(branchPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", branchPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        branch = update(branch);

        return branch;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Branch delete(Integer branchId) {
        LOGGER.debug("Deleting Branch with id: {}", branchId);
        Branch deleted = this.wmGenericDao.findById(branchId);
        if (deleted == null) {
            LOGGER.debug("No Branch found with id: {}", branchId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Branch.class.getSimpleName(), branchId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public void delete(Branch branch) {
        LOGGER.debug("Deleting Branch with {}", branch);
        this.wmGenericDao.delete(branch);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Branch> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Branches");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Branch> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Branches");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service teller_db for table Branch to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service teller_db for table Branch to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Account> findAssociatedAccounts(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated accounts");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("branch.id = '" + id + "'");

        return accountService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Manager> findAssociatedManagers(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated managers");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("branch.id = '" + id + "'");

        return managerService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service ManagerService instance
     */
    protected void setManagerService(ManagerService service) {
        this.managerService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service AccountService instance
     */
    protected void setAccountService(AccountService service) {
        this.accountService = service;
    }

}
