/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Account;
import com.wavemaker.teller_app.teller_db.Customer;


/**
 * ServiceImpl object for domain model class Customer.
 *
 * @see Customer
 */
@Service("teller_db.CustomerService")
@Validated
@EntityService(entityClass = Customer.class, serviceId = "teller_db")
public class CustomerServiceImpl implements CustomerService {

    private static final Logger LOGGER = LoggerFactory.getLogger(CustomerServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("teller_db.AccountService")
    private AccountService accountService;

    @Autowired
    @Qualifier("teller_db.CustomerDao")
    private WMGenericDao<Customer, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<Customer, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Customer create(Customer customer) {
        LOGGER.debug("Creating a new Customer with information: {}", customer);

        Customer customerCreated = this.wmGenericDao.create(customer);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(customerCreated);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Customer getById(Integer customerIdInstance) {
        LOGGER.debug("Finding Customer by id: {}", customerIdInstance);
        return this.wmGenericDao.findById(customerIdInstance);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Customer findById(Integer customerIdInstance) {
        LOGGER.debug("Finding Customer by id: {}", customerIdInstance);
        try {
            return this.wmGenericDao.findById(customerIdInstance);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Customer found with id: {}", customerIdInstance, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public List<Customer> findByMultipleIds(List<Integer> customerIdInstances, boolean orderedReturn) {
        LOGGER.debug("Finding Customers by ids: {}", customerIdInstances);

        return this.wmGenericDao.findByMultipleIds(customerIdInstances, orderedReturn);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Customer getByCustomerId(String customerId) {
        Map<String, Object> customerIdMap = new HashMap<>();
        customerIdMap.put("customerId", customerId);

        LOGGER.debug("Finding Customer by unique keys: {}", customerIdMap);
        return this.wmGenericDao.findByUniqueKey(customerIdMap);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "teller_dbTransactionManager")
    @Override
    public Customer update(Customer customer) {
        LOGGER.debug("Updating Customer with information: {}", customer);

        this.wmGenericDao.update(customer);
        this.wmGenericDao.refresh(customer);

        return customer;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Customer partialUpdate(Integer customerIdInstance, Map<String, Object>customerPatch) {
        LOGGER.debug("Partially Updating the Customer with id: {}", customerIdInstance);

        Customer customer = getById(customerIdInstance);

        try {
            ObjectReader customerReader = WMObjectMapper.getInstance().reader().forType(Customer.class).withValueToUpdate(customer);
            customer = customerReader.readValue(WMObjectMapper.getInstance().writeValueAsString(customerPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", customerPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        customer = update(customer);

        return customer;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Customer delete(Integer customerIdInstance) {
        LOGGER.debug("Deleting Customer with id: {}", customerIdInstance);
        Customer deleted = this.wmGenericDao.findById(customerIdInstance);
        if (deleted == null) {
            LOGGER.debug("No Customer found with id: {}", customerIdInstance);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Customer.class.getSimpleName(), customerIdInstance);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public void delete(Customer customer) {
        LOGGER.debug("Deleting Customer with {}", customer);
        this.wmGenericDao.delete(customer);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Customer> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Customers");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Customer> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Customers");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service teller_db for table Customer to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service teller_db for table Customer to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Account> findAssociatedAccounts(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated accounts");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("customer.id = '" + id + "'");

        return accountService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service AccountService instance
     */
    protected void setAccountService(AccountService service) {
        this.accountService = service;
    }

}
