/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.DepositAccount;


/**
 * ServiceImpl object for domain model class DepositAccount.
 *
 * @see DepositAccount
 */
@Service("teller_db.DepositAccountService")
@Validated
@EntityService(entityClass = DepositAccount.class, serviceId = "teller_db")
public class DepositAccountServiceImpl implements DepositAccountService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DepositAccountServiceImpl.class);


    @Autowired
    @Qualifier("teller_db.DepositAccountDao")
    private WMGenericDao<DepositAccount, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<DepositAccount, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public DepositAccount create(DepositAccount depositAccount) {
        LOGGER.debug("Creating a new DepositAccount with information: {}", depositAccount);

        DepositAccount depositAccountCreated = this.wmGenericDao.create(depositAccount);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(depositAccountCreated);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public DepositAccount getById(Integer depositaccountId) {
        LOGGER.debug("Finding DepositAccount by id: {}", depositaccountId);
        return this.wmGenericDao.findById(depositaccountId);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public DepositAccount findById(Integer depositaccountId) {
        LOGGER.debug("Finding DepositAccount by id: {}", depositaccountId);
        try {
            return this.wmGenericDao.findById(depositaccountId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No DepositAccount found with id: {}", depositaccountId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public List<DepositAccount> findByMultipleIds(List<Integer> depositaccountIds, boolean orderedReturn) {
        LOGGER.debug("Finding DepositAccounts by ids: {}", depositaccountIds);

        return this.wmGenericDao.findByMultipleIds(depositaccountIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "teller_dbTransactionManager")
    @Override
    public DepositAccount update(DepositAccount depositAccount) {
        LOGGER.debug("Updating DepositAccount with information: {}", depositAccount);

        this.wmGenericDao.update(depositAccount);
        this.wmGenericDao.refresh(depositAccount);

        return depositAccount;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public DepositAccount partialUpdate(Integer depositaccountId, Map<String, Object>depositAccountPatch) {
        LOGGER.debug("Partially Updating the DepositAccount with id: {}", depositaccountId);

        DepositAccount depositAccount = getById(depositaccountId);

        try {
            ObjectReader depositAccountReader = WMObjectMapper.getInstance().reader().forType(DepositAccount.class).withValueToUpdate(depositAccount);
            depositAccount = depositAccountReader.readValue(WMObjectMapper.getInstance().writeValueAsString(depositAccountPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", depositAccountPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        depositAccount = update(depositAccount);

        return depositAccount;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public DepositAccount delete(Integer depositaccountId) {
        LOGGER.debug("Deleting DepositAccount with id: {}", depositaccountId);
        DepositAccount deleted = this.wmGenericDao.findById(depositaccountId);
        if (deleted == null) {
            LOGGER.debug("No DepositAccount found with id: {}", depositaccountId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), DepositAccount.class.getSimpleName(), depositaccountId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public void delete(DepositAccount depositAccount) {
        LOGGER.debug("Deleting DepositAccount with {}", depositAccount);
        this.wmGenericDao.delete(depositAccount);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<DepositAccount> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all DepositAccounts");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<DepositAccount> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all DepositAccounts");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service teller_db for table DepositAccount to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service teller_db for table DepositAccount to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
