/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.DepositAccount;

/**
 * Service object for domain model class {@link DepositAccount}.
 */
public interface DepositAccountService {

    /**
     * Creates a new DepositAccount. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on DepositAccount if any.
     *
     * @param depositAccount Details of the DepositAccount to be created; value cannot be null.
     * @return The newly created DepositAccount.
     */
    DepositAccount create(@Valid DepositAccount depositAccount);


	/**
     * Returns DepositAccount by given id if exists.
     *
     * @param depositaccountId The id of the DepositAccount to get; value cannot be null.
     * @return DepositAccount associated with the given depositaccountId.
	 * @throws EntityNotFoundException If no DepositAccount is found.
     */
    DepositAccount getById(Integer depositaccountId);

    /**
     * Find and return the DepositAccount by given id if exists, returns null otherwise.
     *
     * @param depositaccountId The id of the DepositAccount to get; value cannot be null.
     * @return DepositAccount associated with the given depositaccountId.
     */
    DepositAccount findById(Integer depositaccountId);

	/**
     * Find and return the list of DepositAccounts by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param depositaccountIds The id's of the DepositAccount to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return DepositAccounts associated with the given depositaccountIds.
     */
    List<DepositAccount> findByMultipleIds(List<Integer> depositaccountIds, boolean orderedReturn);


    /**
     * Updates the details of an existing DepositAccount. It replaces all fields of the existing DepositAccount with the given depositAccount.
     *
     * This method overrides the input field values using Server side or database managed properties defined on DepositAccount if any.
     *
     * @param depositAccount The details of the DepositAccount to be updated; value cannot be null.
     * @return The updated DepositAccount.
     * @throws EntityNotFoundException if no DepositAccount is found with given input.
     */
    DepositAccount update(@Valid DepositAccount depositAccount);


    /**
     * Partially updates the details of an existing DepositAccount. It updates only the
     * fields of the existing DepositAccount which are passed in the depositAccountPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on DepositAccount if any.
     *
     * @param depositaccountId The id of the DepositAccount to be deleted; value cannot be null.
     * @param depositAccountPatch The partial data of DepositAccount which is supposed to be updated; value cannot be null.
     * @return The updated DepositAccount.
     * @throws EntityNotFoundException if no DepositAccount is found with given input.
     */
    DepositAccount partialUpdate(Integer depositaccountId, Map<String, Object> depositAccountPatch);

    /**
     * Deletes an existing DepositAccount with the given id.
     *
     * @param depositaccountId The id of the DepositAccount to be deleted; value cannot be null.
     * @return The deleted DepositAccount.
     * @throws EntityNotFoundException if no DepositAccount found with the given id.
     */
    DepositAccount delete(Integer depositaccountId);

    /**
     * Deletes an existing DepositAccount with the given object.
     *
     * @param depositAccount The instance of the DepositAccount to be deleted; value cannot be null.
     */
    void delete(DepositAccount depositAccount);

    /**
     * Find all DepositAccounts matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching DepositAccounts.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<DepositAccount> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all DepositAccounts matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching DepositAccounts.
     *
     * @see Pageable
     * @see Page
     */
    Page<DepositAccount> findAll(String query, Pageable pageable);

    /**
     * Exports all DepositAccounts matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all DepositAccounts matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the DepositAccounts in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the DepositAccount.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}
