/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Account;
import com.wavemaker.teller_app.teller_db.Manager;

/**
 * Service object for domain model class {@link Manager}.
 */
public interface ManagerService {

    /**
     * Creates a new Manager. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Manager if any.
     *
     * @param manager Details of the Manager to be created; value cannot be null.
     * @return The newly created Manager.
     */
    Manager create(@Valid Manager manager);


	/**
     * Returns Manager by given id if exists.
     *
     * @param managerIdInstance The id of the Manager to get; value cannot be null.
     * @return Manager associated with the given managerIdInstance.
	 * @throws EntityNotFoundException If no Manager is found.
     */
    Manager getById(Integer managerIdInstance);

    /**
     * Find and return the Manager by given id if exists, returns null otherwise.
     *
     * @param managerIdInstance The id of the Manager to get; value cannot be null.
     * @return Manager associated with the given managerIdInstance.
     */
    Manager findById(Integer managerIdInstance);

	/**
     * Find and return the list of Managers by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param managerIdInstances The id's of the Manager to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Managers associated with the given managerIdInstances.
     */
    List<Manager> findByMultipleIds(List<Integer> managerIdInstances, boolean orderedReturn);

    /**
     * Find and return the Manager for given managerId  if exists.
     *
     * @param managerId value of managerId; value cannot be null.
     * @return Manager associated with the given inputs.
     * @throws EntityNotFoundException if no matching Manager found.
     */
    Manager getByManagerId(String managerId);

    /**
     * Updates the details of an existing Manager. It replaces all fields of the existing Manager with the given manager.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Manager if any.
     *
     * @param manager The details of the Manager to be updated; value cannot be null.
     * @return The updated Manager.
     * @throws EntityNotFoundException if no Manager is found with given input.
     */
    Manager update(@Valid Manager manager);


    /**
     * Partially updates the details of an existing Manager. It updates only the
     * fields of the existing Manager which are passed in the managerPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Manager if any.
     *
     * @param managerIdInstance The id of the Manager to be deleted; value cannot be null.
     * @param managerPatch The partial data of Manager which is supposed to be updated; value cannot be null.
     * @return The updated Manager.
     * @throws EntityNotFoundException if no Manager is found with given input.
     */
    Manager partialUpdate(Integer managerIdInstance, Map<String, Object> managerPatch);

    /**
     * Deletes an existing Manager with the given id.
     *
     * @param managerIdInstance The id of the Manager to be deleted; value cannot be null.
     * @return The deleted Manager.
     * @throws EntityNotFoundException if no Manager found with the given id.
     */
    Manager delete(Integer managerIdInstance);

    /**
     * Deletes an existing Manager with the given object.
     *
     * @param manager The instance of the Manager to be deleted; value cannot be null.
     */
    void delete(Manager manager);

    /**
     * Find all Managers matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Managers.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Manager> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Managers matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Managers.
     *
     * @see Pageable
     * @see Page
     */
    Page<Manager> findAll(String query, Pageable pageable);

    /**
     * Exports all Managers matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Managers matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Managers in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Manager.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated accounts for given Manager id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Account instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Account> findAssociatedAccounts(Integer id, Pageable pageable);

}
