/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Account;
import com.wavemaker.teller_app.teller_db.Manager;


/**
 * ServiceImpl object for domain model class Manager.
 *
 * @see Manager
 */
@Service("teller_db.ManagerService")
@Validated
@EntityService(entityClass = Manager.class, serviceId = "teller_db")
public class ManagerServiceImpl implements ManagerService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ManagerServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("teller_db.AccountService")
    private AccountService accountService;

    @Autowired
    @Qualifier("teller_db.ManagerDao")
    private WMGenericDao<Manager, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<Manager, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Manager create(Manager manager) {
        LOGGER.debug("Creating a new Manager with information: {}", manager);

        Manager managerCreated = this.wmGenericDao.create(manager);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(managerCreated);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Manager getById(Integer managerIdInstance) {
        LOGGER.debug("Finding Manager by id: {}", managerIdInstance);
        return this.wmGenericDao.findById(managerIdInstance);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Manager findById(Integer managerIdInstance) {
        LOGGER.debug("Finding Manager by id: {}", managerIdInstance);
        try {
            return this.wmGenericDao.findById(managerIdInstance);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Manager found with id: {}", managerIdInstance, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public List<Manager> findByMultipleIds(List<Integer> managerIdInstances, boolean orderedReturn) {
        LOGGER.debug("Finding Managers by ids: {}", managerIdInstances);

        return this.wmGenericDao.findByMultipleIds(managerIdInstances, orderedReturn);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Manager getByManagerId(String managerId) {
        Map<String, Object> managerIdMap = new HashMap<>();
        managerIdMap.put("managerId", managerId);

        LOGGER.debug("Finding Manager by unique keys: {}", managerIdMap);
        return this.wmGenericDao.findByUniqueKey(managerIdMap);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "teller_dbTransactionManager")
    @Override
    public Manager update(Manager manager) {
        LOGGER.debug("Updating Manager with information: {}", manager);

        this.wmGenericDao.update(manager);
        this.wmGenericDao.refresh(manager);

        return manager;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Manager partialUpdate(Integer managerIdInstance, Map<String, Object>managerPatch) {
        LOGGER.debug("Partially Updating the Manager with id: {}", managerIdInstance);

        Manager manager = getById(managerIdInstance);

        try {
            ObjectReader managerReader = WMObjectMapper.getInstance().reader().forType(Manager.class).withValueToUpdate(manager);
            manager = managerReader.readValue(WMObjectMapper.getInstance().writeValueAsString(managerPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", managerPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        manager = update(manager);

        return manager;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Manager delete(Integer managerIdInstance) {
        LOGGER.debug("Deleting Manager with id: {}", managerIdInstance);
        Manager deleted = this.wmGenericDao.findById(managerIdInstance);
        if (deleted == null) {
            LOGGER.debug("No Manager found with id: {}", managerIdInstance);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Manager.class.getSimpleName(), managerIdInstance);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public void delete(Manager manager) {
        LOGGER.debug("Deleting Manager with {}", manager);
        this.wmGenericDao.delete(manager);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Manager> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Managers");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Manager> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Managers");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service teller_db for table Manager to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service teller_db for table Manager to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Account> findAssociatedAccounts(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated accounts");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("manager.id = '" + id + "'");

        return accountService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service AccountService instance
     */
    protected void setAccountService(AccountService service) {
        this.accountService = service;
    }

}
