/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.Role;
import com.wavemaker.teller_app.teller_db.User;


/**
 * ServiceImpl object for domain model class Role.
 *
 * @see Role
 */
@Service("teller_db.RoleService")
@Validated
@EntityService(entityClass = Role.class, serviceId = "teller_db")
public class RoleServiceImpl implements RoleService {

    private static final Logger LOGGER = LoggerFactory.getLogger(RoleServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("teller_db.UserService")
    private UserService userService;

    @Autowired
    @Qualifier("teller_db.RoleDao")
    private WMGenericDao<Role, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<Role, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Role create(Role role) {
        LOGGER.debug("Creating a new Role with information: {}", role);

        Role roleCreated = this.wmGenericDao.create(role);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(roleCreated);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Role getById(Integer roleId) {
        LOGGER.debug("Finding Role by id: {}", roleId);
        return this.wmGenericDao.findById(roleId);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Role findById(Integer roleId) {
        LOGGER.debug("Finding Role by id: {}", roleId);
        try {
            return this.wmGenericDao.findById(roleId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Role found with id: {}", roleId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public List<Role> findByMultipleIds(List<Integer> roleIds, boolean orderedReturn) {
        LOGGER.debug("Finding Roles by ids: {}", roleIds);

        return this.wmGenericDao.findByMultipleIds(roleIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "teller_dbTransactionManager")
    @Override
    public Role update(Role role) {
        LOGGER.debug("Updating Role with information: {}", role);

        this.wmGenericDao.update(role);
        this.wmGenericDao.refresh(role);

        return role;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Role partialUpdate(Integer roleId, Map<String, Object>rolePatch) {
        LOGGER.debug("Partially Updating the Role with id: {}", roleId);

        Role role = getById(roleId);

        try {
            ObjectReader roleReader = WMObjectMapper.getInstance().reader().forType(Role.class).withValueToUpdate(role);
            role = roleReader.readValue(WMObjectMapper.getInstance().writeValueAsString(rolePatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", rolePatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        role = update(role);

        return role;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public Role delete(Integer roleId) {
        LOGGER.debug("Deleting Role with id: {}", roleId);
        Role deleted = this.wmGenericDao.findById(roleId);
        if (deleted == null) {
            LOGGER.debug("No Role found with id: {}", roleId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Role.class.getSimpleName(), roleId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public void delete(Role role) {
        LOGGER.debug("Deleting Role with {}", role);
        this.wmGenericDao.delete(role);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Role> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Roles");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Role> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Roles");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service teller_db for table Role to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service teller_db for table Role to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<User> findAssociatedUsers(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated users");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("role.id = '" + id + "'");

        return userService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service UserService instance
     */
    protected void setUserService(UserService service) {
        this.userService = service;
    }

}
