/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.wavemaker.teller_app.teller_db.models.query.*;

public interface Teller_dbQueryExecutorService {

    Page<GetAccountDetailsByCustomerResponse> executeGetAccountDetailsByCustomer(Integer customerId, Pageable pageable);

    void exportGetAccountDetailsByCustomer(Integer customerId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GetDepositAccountsByCustomerResponse> executeGetDepositAccountsByCustomer(Integer customerId, Pageable pageable);

    void exportGetDepositAccountsByCustomer(Integer customerId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    GetCustomerDetailsResponse executeGetCustomerDetails(Integer customerId);

    Page<GetCustomerListDataResponse> executeGetCustomerListData(Pageable pageable);

    void exportGetCustomerListData(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}
