/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.wavemaker.teller_app.teller_db.models.query.*;

@Service
public class Teller_dbQueryExecutorServiceImpl implements Teller_dbQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Teller_dbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("teller_dbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "teller_dbTransactionManager", readOnly = true)
    @Override
    public Page<GetAccountDetailsByCustomerResponse> executeGetAccountDetailsByCustomer(Integer customerId, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("customerId", customerId);

        return queryExecutor.executeNamedQuery("GetAccountDetailsByCustomer", params, GetAccountDetailsByCustomerResponse.class, pageable);
    }

    @Transactional(value = "teller_dbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportGetAccountDetailsByCustomer(Integer customerId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("customerId", customerId);

        QueryProcedureInput<GetAccountDetailsByCustomerResponse> queryInput = new QueryProcedureInput<>("GetAccountDetailsByCustomer", params, GetAccountDetailsByCustomerResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "teller_dbTransactionManager", readOnly = true)
    @Override
    public Page<GetDepositAccountsByCustomerResponse> executeGetDepositAccountsByCustomer(Integer customerId, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("customerId", customerId);

        return queryExecutor.executeNamedQuery("GetDepositAccountsByCustomer", params, GetDepositAccountsByCustomerResponse.class, pageable);
    }

    @Transactional(value = "teller_dbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportGetDepositAccountsByCustomer(Integer customerId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("customerId", customerId);

        QueryProcedureInput<GetDepositAccountsByCustomerResponse> queryInput = new QueryProcedureInput<>("GetDepositAccountsByCustomer", params, GetDepositAccountsByCustomerResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "teller_dbTransactionManager", readOnly = true)
    @Override
    public GetCustomerDetailsResponse executeGetCustomerDetails(Integer customerId) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("customerId", customerId);

        return queryExecutor.executeNamedQuery("GetCustomerDetails", params, GetCustomerDetailsResponse.class);
    }

    @Transactional(value = "teller_dbTransactionManager", readOnly = true)
    @Override
    public Page<GetCustomerListDataResponse> executeGetCustomerListData(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("getCustomerListData", params, GetCustomerListDataResponse.class, pageable);
    }

    @Transactional(value = "teller_dbTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportGetCustomerListData(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<GetCustomerListDataResponse> queryInput = new QueryProcedureInput<>("getCustomerListData", params, GetCustomerListDataResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}
