/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.WMObjectMapper;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.TransactionHistory;


/**
 * ServiceImpl object for domain model class TransactionHistory.
 *
 * @see TransactionHistory
 */
@Service("teller_db.TransactionHistoryService")
@Validated
@EntityService(entityClass = TransactionHistory.class, serviceId = "teller_db")
public class TransactionHistoryServiceImpl implements TransactionHistoryService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TransactionHistoryServiceImpl.class);


    @Autowired
    @Qualifier("teller_db.TransactionHistoryDao")
    private WMGenericDao<TransactionHistory, Integer> wmGenericDao;


    public void setWMGenericDao(WMGenericDao<TransactionHistory, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public TransactionHistory create(TransactionHistory transactionHistory) {
        LOGGER.debug("Creating a new TransactionHistory with information: {}", transactionHistory);

        TransactionHistory transactionHistoryCreated = this.wmGenericDao.create(transactionHistory);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(transactionHistoryCreated);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public TransactionHistory getById(Integer transactionhistoryId) {
        LOGGER.debug("Finding TransactionHistory by id: {}", transactionhistoryId);
        return this.wmGenericDao.findById(transactionhistoryId);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public TransactionHistory findById(Integer transactionhistoryId) {
        LOGGER.debug("Finding TransactionHistory by id: {}", transactionhistoryId);
        try {
            return this.wmGenericDao.findById(transactionhistoryId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No TransactionHistory found with id: {}", transactionhistoryId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public List<TransactionHistory> findByMultipleIds(List<Integer> transactionhistoryIds, boolean orderedReturn) {
        LOGGER.debug("Finding TransactionHistories by ids: {}", transactionhistoryIds);

        return this.wmGenericDao.findByMultipleIds(transactionhistoryIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "teller_dbTransactionManager")
    @Override
    public TransactionHistory update(TransactionHistory transactionHistory) {
        LOGGER.debug("Updating TransactionHistory with information: {}", transactionHistory);

        this.wmGenericDao.update(transactionHistory);
        this.wmGenericDao.refresh(transactionHistory);

        return transactionHistory;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public TransactionHistory partialUpdate(Integer transactionhistoryId, Map<String, Object>transactionHistoryPatch) {
        LOGGER.debug("Partially Updating the TransactionHistory with id: {}", transactionhistoryId);

        TransactionHistory transactionHistory = getById(transactionhistoryId);

        try {
            ObjectReader transactionHistoryReader = WMObjectMapper.getInstance().reader().forType(TransactionHistory.class).withValueToUpdate(transactionHistory);
            transactionHistory = transactionHistoryReader.readValue(WMObjectMapper.getInstance().writeValueAsString(transactionHistoryPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", transactionHistoryPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        transactionHistory = update(transactionHistory);

        return transactionHistory;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public TransactionHistory delete(Integer transactionhistoryId) {
        LOGGER.debug("Deleting TransactionHistory with id: {}", transactionhistoryId);
        TransactionHistory deleted = this.wmGenericDao.findById(transactionhistoryId);
        if (deleted == null) {
            LOGGER.debug("No TransactionHistory found with id: {}", transactionhistoryId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), TransactionHistory.class.getSimpleName(), transactionhistoryId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "teller_dbTransactionManager")
    @Override
    public void delete(TransactionHistory transactionHistory) {
        LOGGER.debug("Deleting TransactionHistory with {}", transactionHistory);
        this.wmGenericDao.delete(transactionHistory);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<TransactionHistory> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all TransactionHistories");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<TransactionHistory> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all TransactionHistories");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service teller_db for table TransactionHistory to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service teller_db for table TransactionHistory to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "teller_dbTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}
