/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import jakarta.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.teller_app.teller_db.TransactionHistory;

/**
 * Service object for domain model class {@link TransactionHistory}.
 */
public interface TransactionHistoryService {

    /**
     * Creates a new TransactionHistory. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on TransactionHistory if any.
     *
     * @param transactionHistory Details of the TransactionHistory to be created; value cannot be null.
     * @return The newly created TransactionHistory.
     */
    TransactionHistory create(@Valid TransactionHistory transactionHistory);


	/**
     * Returns TransactionHistory by given id if exists.
     *
     * @param transactionhistoryId The id of the TransactionHistory to get; value cannot be null.
     * @return TransactionHistory associated with the given transactionhistoryId.
	 * @throws EntityNotFoundException If no TransactionHistory is found.
     */
    TransactionHistory getById(Integer transactionhistoryId);

    /**
     * Find and return the TransactionHistory by given id if exists, returns null otherwise.
     *
     * @param transactionhistoryId The id of the TransactionHistory to get; value cannot be null.
     * @return TransactionHistory associated with the given transactionhistoryId.
     */
    TransactionHistory findById(Integer transactionhistoryId);

	/**
     * Find and return the list of TransactionHistories by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param transactionhistoryIds The id's of the TransactionHistory to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return TransactionHistories associated with the given transactionhistoryIds.
     */
    List<TransactionHistory> findByMultipleIds(List<Integer> transactionhistoryIds, boolean orderedReturn);


    /**
     * Updates the details of an existing TransactionHistory. It replaces all fields of the existing TransactionHistory with the given transactionHistory.
     *
     * This method overrides the input field values using Server side or database managed properties defined on TransactionHistory if any.
     *
     * @param transactionHistory The details of the TransactionHistory to be updated; value cannot be null.
     * @return The updated TransactionHistory.
     * @throws EntityNotFoundException if no TransactionHistory is found with given input.
     */
    TransactionHistory update(@Valid TransactionHistory transactionHistory);


    /**
     * Partially updates the details of an existing TransactionHistory. It updates only the
     * fields of the existing TransactionHistory which are passed in the transactionHistoryPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on TransactionHistory if any.
     *
     * @param transactionhistoryId The id of the TransactionHistory to be deleted; value cannot be null.
     * @param transactionHistoryPatch The partial data of TransactionHistory which is supposed to be updated; value cannot be null.
     * @return The updated TransactionHistory.
     * @throws EntityNotFoundException if no TransactionHistory is found with given input.
     */
    TransactionHistory partialUpdate(Integer transactionhistoryId, Map<String, Object> transactionHistoryPatch);

    /**
     * Deletes an existing TransactionHistory with the given id.
     *
     * @param transactionhistoryId The id of the TransactionHistory to be deleted; value cannot be null.
     * @return The deleted TransactionHistory.
     * @throws EntityNotFoundException if no TransactionHistory found with the given id.
     */
    TransactionHistory delete(Integer transactionhistoryId);

    /**
     * Deletes an existing TransactionHistory with the given object.
     *
     * @param transactionHistory The instance of the TransactionHistory to be deleted; value cannot be null.
     */
    void delete(TransactionHistory transactionHistory);

    /**
     * Find all TransactionHistories matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching TransactionHistories.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<TransactionHistory> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all TransactionHistories matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching TransactionHistories.
     *
     * @see Pageable
     * @see Page
     */
    Page<TransactionHistory> findAll(String query, Pageable pageable);

    /**
     * Exports all TransactionHistories matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all TransactionHistories matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the TransactionHistories in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the TransactionHistory.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}
