/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.depositorchestrationservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.teller_app.depositorchestrationservice.DepositOrchestrationService;
import com.wavemaker.teller_app.depositorchestrationservice.model.DepositResponse;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link DepositOrchestrationService}.
 * @see DepositOrchestrationService
 */
@RestController
@Api(value = "DepositOrchestrationController", description = "controller class for java service execution")
@RequestMapping("/depositOrchestration")
public class DepositOrchestrationController {

    @Autowired
    private DepositOrchestrationService depositOrchestrationService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @PostMapping(value = "/deposit")
    public DepositResponse createDeposit(@RequestParam(value = "accountId", required = false) Integer accountId, @RequestParam(value = "termDeposit", required = false) Double termDeposit, @RequestParam(value = "rateOfInterest", required = false) Double rateOfInterest, @RequestParam(value = "maturityAmount", required = false) Double maturityAmount, @RequestParam(value = "depositedAt", required = false) Long depositedAt, @RequestParam(value = "maturedAt", required = false) Long maturedAt, @RequestParam(value = "depositStatus", required = false) String depositStatus, @RequestParam(value = "currentBalance", required = false) Double currentBalance, @RequestParam(value = "balanceId", required = false) Integer balanceId) {
        return depositOrchestrationService.createDeposit(accountId, termDeposit, rateOfInterest, maturityAmount, depositedAt, maturedAt, depositStatus, currentBalance, balanceId);
    }
}
