/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetAccountDetailsByCustomerResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("account_number")
    private Integer accountNumber;

    @ColumnAlias("type")
    private String type;

    @ColumnAlias("status")
    private String status;

    @ColumnAlias("activated_from")
    private String activatedFrom;

    @ColumnAlias("activate_to")
    private String activateTo;

    @ColumnAlias("branch_name")
    private String branchName;

    @ColumnAlias("branch_code")
    private String branchCode;

    @ColumnAlias("branch_address1")
    private String branchAddress1;

    @ColumnAlias("branch_city")
    private String branchCity;

    @ColumnAlias("branch_state")
    private String branchState;

    @ColumnAlias("branch_pin")
    private String branchPin;

    @ColumnAlias("manager_name")
    private String managerName;

    @ColumnAlias("manager_id")
    private String managerId;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(Integer accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getActivatedFrom() {
        return this.activatedFrom;
    }

    public void setActivatedFrom(String activatedFrom) {
        this.activatedFrom = activatedFrom;
    }

    public String getActivateTo() {
        return this.activateTo;
    }

    public void setActivateTo(String activateTo) {
        this.activateTo = activateTo;
    }

    public String getBranchName() {
        return this.branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getBranchCode() {
        return this.branchCode;
    }

    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    public String getBranchAddress1() {
        return this.branchAddress1;
    }

    public void setBranchAddress1(String branchAddress1) {
        this.branchAddress1 = branchAddress1;
    }

    public String getBranchCity() {
        return this.branchCity;
    }

    public void setBranchCity(String branchCity) {
        this.branchCity = branchCity;
    }

    public String getBranchState() {
        return this.branchState;
    }

    public void setBranchState(String branchState) {
        this.branchState = branchState;
    }

    public String getBranchPin() {
        return this.branchPin;
    }

    public void setBranchPin(String branchPin) {
        this.branchPin = branchPin;
    }

    public String getManagerName() {
        return this.managerName;
    }

    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    public String getManagerId() {
        return this.managerId;
    }

    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetAccountDetailsByCustomerResponse)) return false;
        final GetAccountDetailsByCustomerResponse getAccountDetailsByCustomerResponse = (GetAccountDetailsByCustomerResponse) o;
        return Objects.equals(getId(), getAccountDetailsByCustomerResponse.getId()) &&
                Objects.equals(getAccountNumber(), getAccountDetailsByCustomerResponse.getAccountNumber()) &&
                Objects.equals(getType(), getAccountDetailsByCustomerResponse.getType()) &&
                Objects.equals(getStatus(), getAccountDetailsByCustomerResponse.getStatus()) &&
                Objects.equals(getActivatedFrom(), getAccountDetailsByCustomerResponse.getActivatedFrom()) &&
                Objects.equals(getActivateTo(), getAccountDetailsByCustomerResponse.getActivateTo()) &&
                Objects.equals(getBranchName(), getAccountDetailsByCustomerResponse.getBranchName()) &&
                Objects.equals(getBranchCode(), getAccountDetailsByCustomerResponse.getBranchCode()) &&
                Objects.equals(getBranchAddress1(), getAccountDetailsByCustomerResponse.getBranchAddress1()) &&
                Objects.equals(getBranchCity(), getAccountDetailsByCustomerResponse.getBranchCity()) &&
                Objects.equals(getBranchState(), getAccountDetailsByCustomerResponse.getBranchState()) &&
                Objects.equals(getBranchPin(), getAccountDetailsByCustomerResponse.getBranchPin()) &&
                Objects.equals(getManagerName(), getAccountDetailsByCustomerResponse.getManagerName()) &&
                Objects.equals(getManagerId(), getAccountDetailsByCustomerResponse.getManagerId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getAccountNumber(),
                getType(),
                getStatus(),
                getActivatedFrom(),
                getActivateTo(),
                getBranchName(),
                getBranchCode(),
                getBranchAddress1(),
                getBranchCity(),
                getBranchState(),
                getBranchPin(),
                getManagerName(),
                getManagerId());
    }
}
