/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetCustomerDetailsResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("customer_id")
    private String customerId;

    @ColumnAlias("firstname")
    private String firstname;

    @ColumnAlias("lastname")
    private String lastname;

    @ColumnAlias("phone")
    private String phone;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("id_proof")
    private String idProof;

    @ColumnAlias("resident_status")
    private String residentStatus;

    @ColumnAlias("time_zone")
    private String timeZone;

    @ColumnAlias("created_at")
    private LocalDateTime createdAt;

    @ColumnAlias("city")
    private String city;

    @ColumnAlias("address1")
    private String address1;

    @ColumnAlias("address2")
    private String address2;

    @ColumnAlias("state")
    private String state;

    @ColumnAlias("pin")
    private String pin;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getIdProof() {
        return this.idProof;
    }

    public void setIdProof(String idProof) {
        this.idProof = idProof;
    }

    public String getResidentStatus() {
        return this.residentStatus;
    }

    public void setResidentStatus(String residentStatus) {
        this.residentStatus = residentStatus;
    }

    public String getTimeZone() {
        return this.timeZone;
    }

    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getPin() {
        return this.pin;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetCustomerDetailsResponse)) return false;
        final GetCustomerDetailsResponse getCustomerDetailsResponse = (GetCustomerDetailsResponse) o;
        return Objects.equals(getId(), getCustomerDetailsResponse.getId()) &&
                Objects.equals(getCustomerId(), getCustomerDetailsResponse.getCustomerId()) &&
                Objects.equals(getFirstname(), getCustomerDetailsResponse.getFirstname()) &&
                Objects.equals(getLastname(), getCustomerDetailsResponse.getLastname()) &&
                Objects.equals(getPhone(), getCustomerDetailsResponse.getPhone()) &&
                Objects.equals(getEmail(), getCustomerDetailsResponse.getEmail()) &&
                Objects.equals(getIdProof(), getCustomerDetailsResponse.getIdProof()) &&
                Objects.equals(getResidentStatus(), getCustomerDetailsResponse.getResidentStatus()) &&
                Objects.equals(getTimeZone(), getCustomerDetailsResponse.getTimeZone()) &&
                Objects.equals(getCreatedAt(), getCustomerDetailsResponse.getCreatedAt()) &&
                Objects.equals(getCity(), getCustomerDetailsResponse.getCity()) &&
                Objects.equals(getAddress1(), getCustomerDetailsResponse.getAddress1()) &&
                Objects.equals(getAddress2(), getCustomerDetailsResponse.getAddress2()) &&
                Objects.equals(getState(), getCustomerDetailsResponse.getState()) &&
                Objects.equals(getPin(), getCustomerDetailsResponse.getPin());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getCustomerId(),
                getFirstname(),
                getLastname(),
                getPhone(),
                getEmail(),
                getIdProof(),
                getResidentStatus(),
                getTimeZone(),
                getCreatedAt(),
                getCity(),
                getAddress1(),
                getAddress2(),
                getState(),
                getPin());
    }
}
