/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetCustomerListDataResponse implements Serializable {


    @ColumnAlias("customerid")
    private Integer customerid;

    @ColumnAlias("customercode")
    private String customercode;

    @ColumnAlias("firstname")
    private String firstname;

    @ColumnAlias("lastname")
    private String lastname;

    @ColumnAlias("phone")
    private String phone;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("totalbalance")
    private BigDecimal totalbalance;

    @ColumnAlias("branchname")
    private String branchname;

    @ColumnAlias("branchcity")
    private String branchcity;

    @ColumnAlias("accountcount")
    private Long accountcount;

    @ColumnAlias("managername")
    private String managername;

    @ColumnAlias("managercity")
    private String managercity;

    @ColumnAlias("accountstatussummary")
    private String accountstatussummary;

    public Integer getCustomerid() {
        return this.customerid;
    }

    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    public String getCustomercode() {
        return this.customercode;
    }

    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public BigDecimal getTotalbalance() {
        return this.totalbalance;
    }

    public void setTotalbalance(BigDecimal totalbalance) {
        this.totalbalance = totalbalance;
    }

    public String getBranchname() {
        return this.branchname;
    }

    public void setBranchname(String branchname) {
        this.branchname = branchname;
    }

    public String getBranchcity() {
        return this.branchcity;
    }

    public void setBranchcity(String branchcity) {
        this.branchcity = branchcity;
    }

    public Long getAccountcount() {
        return this.accountcount;
    }

    public void setAccountcount(Long accountcount) {
        this.accountcount = accountcount;
    }

    public String getManagername() {
        return this.managername;
    }

    public void setManagername(String managername) {
        this.managername = managername;
    }

    public String getManagercity() {
        return this.managercity;
    }

    public void setManagercity(String managercity) {
        this.managercity = managercity;
    }

    public String getAccountstatussummary() {
        return this.accountstatussummary;
    }

    public void setAccountstatussummary(String accountstatussummary) {
        this.accountstatussummary = accountstatussummary;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetCustomerListDataResponse)) return false;
        final GetCustomerListDataResponse getCustomerListDataResponse = (GetCustomerListDataResponse) o;
        return Objects.equals(getCustomerid(), getCustomerListDataResponse.getCustomerid()) &&
                Objects.equals(getCustomercode(), getCustomerListDataResponse.getCustomercode()) &&
                Objects.equals(getFirstname(), getCustomerListDataResponse.getFirstname()) &&
                Objects.equals(getLastname(), getCustomerListDataResponse.getLastname()) &&
                Objects.equals(getPhone(), getCustomerListDataResponse.getPhone()) &&
                Objects.equals(getEmail(), getCustomerListDataResponse.getEmail()) &&
                Objects.equals(getTotalbalance(), getCustomerListDataResponse.getTotalbalance()) &&
                Objects.equals(getBranchname(), getCustomerListDataResponse.getBranchname()) &&
                Objects.equals(getBranchcity(), getCustomerListDataResponse.getBranchcity()) &&
                Objects.equals(getAccountcount(), getCustomerListDataResponse.getAccountcount()) &&
                Objects.equals(getManagername(), getCustomerListDataResponse.getManagername()) &&
                Objects.equals(getManagercity(), getCustomerListDataResponse.getManagercity()) &&
                Objects.equals(getAccountstatussummary(), getCustomerListDataResponse.getAccountstatussummary());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCustomerid(),
                getCustomercode(),
                getFirstname(),
                getLastname(),
                getPhone(),
                getEmail(),
                getTotalbalance(),
                getBranchname(),
                getBranchcity(),
                getAccountcount(),
                getManagername(),
                getManagercity(),
                getAccountstatussummary());
    }
}
