/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.teller_app.teller_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetDepositAccountsByCustomerResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("term_deposit")
    private Double termDeposit;

    @ColumnAlias("maturity_amount")
    private Double maturityAmount;

    @ColumnAlias("rate_of_interest")
    private Double rateOfInterest;

    @ColumnAlias("deposited_at")
    private Date depositedAt;

    @ColumnAlias("matured_at")
    private Date maturedAt;

    @ColumnAlias("status")
    private String status;

    @ColumnAlias("account_number")
    private Integer accountNumber;

    @ColumnAlias("account_type")
    private String accountType;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Double getTermDeposit() {
        return this.termDeposit;
    }

    public void setTermDeposit(Double termDeposit) {
        this.termDeposit = termDeposit;
    }

    public Double getMaturityAmount() {
        return this.maturityAmount;
    }

    public void setMaturityAmount(Double maturityAmount) {
        this.maturityAmount = maturityAmount;
    }

    public Double getRateOfInterest() {
        return this.rateOfInterest;
    }

    public void setRateOfInterest(Double rateOfInterest) {
        this.rateOfInterest = rateOfInterest;
    }

    public Date getDepositedAt() {
        return this.depositedAt;
    }

    public void setDepositedAt(Date depositedAt) {
        this.depositedAt = depositedAt;
    }

    public Date getMaturedAt() {
        return this.maturedAt;
    }

    public void setMaturedAt(Date maturedAt) {
        this.maturedAt = maturedAt;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(Integer accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getAccountType() {
        return this.accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetDepositAccountsByCustomerResponse)) return false;
        final GetDepositAccountsByCustomerResponse getDepositAccountsByCustomerResponse = (GetDepositAccountsByCustomerResponse) o;
        return Objects.equals(getId(), getDepositAccountsByCustomerResponse.getId()) &&
                Objects.equals(getTermDeposit(), getDepositAccountsByCustomerResponse.getTermDeposit()) &&
                Objects.equals(getMaturityAmount(), getDepositAccountsByCustomerResponse.getMaturityAmount()) &&
                Objects.equals(getRateOfInterest(), getDepositAccountsByCustomerResponse.getRateOfInterest()) &&
                Objects.equals(getDepositedAt(), getDepositAccountsByCustomerResponse.getDepositedAt()) &&
                Objects.equals(getMaturedAt(), getDepositAccountsByCustomerResponse.getMaturedAt()) &&
                Objects.equals(getStatus(), getDepositAccountsByCustomerResponse.getStatus()) &&
                Objects.equals(getAccountNumber(), getDepositAccountsByCustomerResponse.getAccountNumber()) &&
                Objects.equals(getAccountType(), getDepositAccountsByCustomerResponse.getAccountType());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getTermDeposit(),
                getMaturityAmount(),
                getRateOfInterest(),
                getDepositedAt(),
                getMaturedAt(),
                getStatus(),
                getAccountNumber(),
                getAccountType());
    }
}
